//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHSSVEntities : DbContext
    {
        public QLHSSVEntities()
            : base("name=QLHSSVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KHOAVIEN> KHOAVIENs { get; set; }
        public virtual DbSet<KTX> KTXes { get; set; }
        public virtual DbSet<LOAIHINHDT> LOAIHINHDTs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<NGANH> NGANHs { get; set; }
        public virtual DbSet<NGOAITRU> NGOAITRUs { get; set; }
        public virtual DbSet<NGUOITHAN> NGUOITHANs { get; set; }
        public virtual DbSet<NOITRU> NOITRUs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
